### ISSUE TITLE
Not installable for IntelliJ Ultimate 2021.3

### ISSUE THREAD

**Issue by cawolf** [bridgecrewio/checkov-jetbrains-ide#72]
Hi,

I just received an email about the availability of this plugin and was delighted!

However, when I started my system, Jetbrains already released version 2021.3 of IntelliJ Ultimate, and my system installed it automatically, leading to me not being able to find your plugin in the marketplace, because your plugin's version constraint doesn't allow for products > 2021.2.3.

As a Jetbrains plugin developer myself, I already ran into this issue, and my take on it was to open up the upper bound to not being forced to immediately take action whenever Jetbrains releases a new product version.

Whether you follow that approach or just simply increase the upper version bound - I would really like to use your plugin in my newest IDE :) 

Thanks in advance,
best regards,
@cawolf

**Comment by orhovy** [comment]
@cawolf There is an open PR regarding removing the upper bound of the plugin , will be updated on the next version.
Thanks for letting us know :)

**Comment by orhovy** [comment]
was fixed in https://github.com/bridgecrewio/checkov-jetbrains-ide/pull/71
